### ISSUE TITLE
Parts list?

### ISSUE THREAD

**Issue by nardev** [Irdroid/Irdroid-Rpi#1]
hello,

nice project, wondering what is the transistor used for IR diodes and why did you need BAP64 there?

thnx

**Comment by Irdroid** [comment]
Parts list is included in the Eagle Schematic file

**Comment by Irdroid** [comment]
The Transistor could be any NPN SMT transistor that can handle > 250mA of current

**Comment by nardev** [comment]
thank you very much....

**Comment by nardev** [comment]
and BAP64?

**Comment by Irdroid** [comment]
yes, BAP64 SMD

**Comment by nardev** [comment]
:D the question was "why did you need BAP64 there?"

**Comment by nardev** [comment]
SOrry, didn't notice it was grounded.. i got it now...
